// File generated by hgctl. Modify as required.
// See: https://higress.io/zh-cn/docs/user/wasm-go#2-%E7%BC%96%E5%86%99-maingo-%E6%96%87%E4%BB%B6

package main

import (
	"fmt"
	"net/url"
	"regexp"
	"strings"

	"github.com/alibaba/higress/plugins/wasm-go/extensions/ai-proxy/config"
	"github.com/alibaba/higress/plugins/wasm-go/extensions/ai-proxy/provider"
	"github.com/alibaba/higress/plugins/wasm-go/extensions/ai-proxy/util"

	"github.com/higress-group/wasm-go/pkg/log"
	"github.com/higress-group/wasm-go/pkg/wrapper"

	"github.com/higress-group/proxy-wasm-go-sdk/proxywasm"
	"github.com/higress-group/proxy-wasm-go-sdk/proxywasm/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

const (
	pluginName = "ai-proxy"

	defaultMaxBodyBytes uint32 = 100 * 1024 * 1024

	ctxStreamIncludeUsage = "original_stream_include_usage"
)

type pair[K, V any] struct {
	key   K
	value V
}

var (
	pathSuffixToApiName = []pair[string, provider.ApiName]{
		// OpenAI style
		{provider.PathOpenAIChatCompletions, provider.ApiNameChatCompletion},
		{provider.PathOpenAICompletions, provider.ApiNameCompletion},
		{provider.PathOpenAIEmbeddings, provider.ApiNameEmbeddings},
		{provider.PathOpenAIAudioSpeech, provider.ApiNameAudioSpeech},
		{provider.PathOpenAIImageGeneration, provider.ApiNameImageGeneration},
		{provider.PathOpenAIImageVariation, provider.ApiNameImageVariation},
		{provider.PathOpenAIImageEdit, provider.ApiNameImageEdit},
		{provider.PathOpenAIBatches, provider.ApiNameBatches},
		{provider.PathOpenAIFiles, provider.ApiNameFiles},
		{provider.PathOpenAIModels, provider.ApiNameModels},
		{provider.PathOpenAIFineTuningJobs, provider.ApiNameFineTuningJobs},
		{provider.PathOpenAIResponses, provider.ApiNameResponses},
		// Anthropic style
		{provider.PathAnthropicMessages, provider.ApiNameAnthropicMessages},
		{provider.PathAnthropicComplete, provider.ApiNameAnthropicComplete},
		// Cohere style
		{provider.PathCohereV1Rerank, provider.ApiNameCohereV1Rerank},
	}
	pathPatternToApiName = []pair[*regexp.Regexp, provider.ApiName]{
		// OpenAI style
		{util.RegRetrieveBatchPath, provider.ApiNameRetrieveBatch},
		{util.RegCancelBatchPath, provider.ApiNameCancelBatch},
		{util.RegRetrieveFilePath, provider.ApiNameRetrieveFile},
		{util.RegRetrieveFileContentPath, provider.ApiNameRetrieveFileContent},
		{util.RegRetrieveFineTuningJobPath, provider.ApiNameRetrieveFineTuningJob},
		{util.RegRetrieveFineTuningJobEventsPath, provider.ApiNameFineTuningJobEvents},
		{util.RegRetrieveFineTuningJobCheckpointsPath, provider.ApiNameFineTuningJobCheckpoints},
		{util.RegCancelFineTuningJobPath, provider.ApiNameCancelFineTuningJob},
		{util.RegResumeFineTuningJobPath, provider.ApiNameResumeFineTuningJob},
		{util.RegPauseFineTuningJobPath, provider.ApiNamePauseFineTuningJob},
		{util.RegFineTuningCheckpointPermissionPath, provider.ApiNameFineTuningCheckpointPermissions},
		{util.RegDeleteFineTuningCheckpointPermissionPath, provider.ApiNameDeleteFineTuningCheckpointPermission},
		// Gemini style
		{util.RegGeminiGenerateContent, provider.ApiNameGeminiGenerateContent},
		{util.RegGeminiStreamGenerateContent, provider.ApiNameGeminiStreamGenerateContent},
	}
)

func main() {}

func init() {
	wrapper.SetCtx(
		pluginName,
		wrapper.ParseOverrideConfig(parseGlobalConfig, parseOverrideRuleConfig),
		wrapper.ProcessRequestHeaders(onHttpRequestHeader),
		wrapper.ProcessRequestBody(onHttpRequestBody),
		wrapper.ProcessResponseHeaders(onHttpResponseHeaders),
		wrapper.ProcessStreamingResponseBody(onStreamingResponseBody),
		wrapper.ProcessResponseBody(onHttpResponseBody),
		wrapper.WithRebuildAfterRequests[config.PluginConfig](1000),
		wrapper.WithRebuildMaxMemBytes[config.PluginConfig](200*1024*1024),
	)
	// Start - Added by Trip.com
	addPathSuffixWithoutV1()
	// End - Added by Trip.com
}

// Start - Added by Trip.com
func addPathSuffixWithoutV1() {
	var extraPathSuffixToApiName []pair[string, provider.ApiName]
	for _, p := range pathSuffixToApiName {
		if strings.HasPrefix(p.key, "/v1/") {
			// Add the same suffix without /v1
			extraPathSuffixToApiName = append(extraPathSuffixToApiName, pair[string, provider.ApiName]{key: p.key[3:], value: p.value})
		}
	}
	pathSuffixToApiName = append(pathSuffixToApiName, extraPathSuffixToApiName...)
}

// End - Added by Trip.com

func parseGlobalConfig(json gjson.Result, pluginConfig *config.PluginConfig) error {
	log.Debugf("loading global config: %s", json.String())

	pluginConfig.FromJson(json)
	if err := pluginConfig.Validate(); err != nil {
		log.Errorf("global rule config is invalid: %v", err)
		return err
	}
	if err := pluginConfig.Complete(); err != nil {
		log.Errorf("failed to apply global rule config: %v", err)
		return err
	}

	return nil
}

func parseOverrideRuleConfig(json gjson.Result, global config.PluginConfig, pluginConfig *config.PluginConfig) error {
	log.Debugf("loading override rule config: %s", json.String())

	*pluginConfig = global

	pluginConfig.FromJson(json)
	if err := pluginConfig.Validate(); err != nil {
		log.Errorf("overriden rule config is invalid: %v", err)
		return err
	}
	if err := pluginConfig.Complete(); err != nil {
		log.Errorf("failed to apply overriden rule config: %v", err)
		return err
	}

	return nil
}

func onHttpRequestHeader(ctx wrapper.HttpContext, pluginConfig config.PluginConfig) types.Action {
	activeProvider := pluginConfig.GetProvider()

	if activeProvider == nil {
		log.Debugf("[onHttpRequestHeader] no active provider, skip processing, path: %s", ctx.Path())
		ctx.DontReadRequestBody()
		return types.ActionContinue
	}

	log.Debugf("[onHttpRequestHeader] provider=%s", activeProvider.GetProviderType())

	// Disable the route re-calculation since the plugin may modify some headers related to the chosen route.
	ctx.DisableReroute()

	rawPath := ctx.Path()
	rawHost, _ := proxywasm.GetHttpRequestHeader(util.HeaderAuthority)
	rawAuth, _ := proxywasm.GetHttpRequestHeader(util.HeaderAuthorization)

	defer saveOriginalHeaders(rawHost, rawPath, rawAuth)

	path, _ := url.Parse(rawPath)
	apiName := getApiName(path.Path)
	providerConfig := pluginConfig.GetProviderConfig()
	provider.SaveProtocolToContext(ctx, providerConfig)
	if provider.IsOriginalProtocol(ctx) {
		if handler, ok := activeProvider.(provider.ApiNameHandler); ok {
			apiName = handler.GetApiName(path.Path)
		}
	}

	// Auto-detect protocol based on request path and handle conversion if needed
	// If request is Claude format (/v1/messages) but provider doesn't support it natively,
	// convert to OpenAI format (/v1/chat/completions)
	if apiName == provider.ApiNameAnthropicMessages && !providerConfig.IsSupportedAPI(provider.ApiNameAnthropicMessages) {
		// Provider doesn't support Claude protocol natively, convert to OpenAI format
		newPath := strings.Replace(path.Path, provider.PathAnthropicMessages, provider.PathOpenAIChatCompletions, 1)
		_ = proxywasm.ReplaceHttpRequestHeader(":path", newPath)
		// Update apiName to match the new path
		apiName = provider.ApiNameChatCompletion
		// Mark that we need to convert response back to Claude format
		ctx.SetContext("needClaudeResponseConversion", true)
		log.Debugf("[Auto Protocol] Claude request detected, provider doesn't support natively, converted path from %s to %s, apiName: %s", path.Path, newPath, apiName)
	} else if apiName == provider.ApiNameAnthropicMessages {
		// Provider supports Claude protocol natively, no conversion needed
		log.Debugf("[Auto Protocol] Claude request detected, provider supports natively, keeping original path: %s, apiName: %s", path.Path, apiName)
	}

	if contentType, _ := proxywasm.GetHttpRequestHeader(util.HeaderContentType); contentType != "" && !strings.Contains(contentType, util.MimeTypeApplicationJson) {
		ctx.DontReadRequestBody()
		log.Debugf("[onHttpRequestHeader] unsupported content type: %s, will not process the request body", contentType)
	}

	if apiName == "" {
		ctx.DontReadRequestBody()
		ctx.DontReadResponseBody()
		if !provider.IsGenericProvider(activeProvider) {
			log.Warnf("[onHttpRequestHeader] unsupported path: %s, will not process http path and body", path.Path)
		}
	}

	ctx.SetContext(provider.CtxKeyApiName, apiName)

	// Always remove the Accept-Encoding header to prevent the LLM from sending compressed responses,
	// allowing plugins to inspect or modify the response correctly
	_ = proxywasm.RemoveHttpRequestHeader("Accept-Encoding")

	if handler, ok := activeProvider.(provider.RequestHeadersHandler); ok {
		// Set the apiToken for the current request.
		providerConfig.SetApiTokenInUse(ctx)
		// Set available apiTokens of current request in the context, will be used in the retryOnFailure
		providerConfig.SetAvailableApiTokens(ctx)

		// save the original request host and path in case they are needed for apiToken health check and retry
		ctx.SetContext(provider.CtxRequestHost, ctx.Host())
		ctx.SetContext(provider.CtxRequestPath, ctx.Path())

		err := handler.OnRequestHeaders(ctx, apiName)
		if err != nil {
			_ = util.ErrorHandler("ai-proxy.proc_req_headers_failed", fmt.Errorf("failed to process request headers: %v", err))
			return types.ActionContinue
		}

		rewriteResponsesBridgePathIfNeeded(ctx, providerConfig, apiName)

		hasRequestBody := ctx.HasRequestBody()
		if hasRequestBody {
			_ = proxywasm.RemoveHttpRequestHeader("Content-Length")
			ctx.SetRequestBodyBufferLimit(defaultMaxBodyBytes)
			// Delay the header processing to allow changing in OnRequestBody
			return types.HeaderStopIteration
		}

		ctx.DontReadRequestBody()
	} else {
		rewriteResponsesBridgePathIfNeeded(ctx, providerConfig, apiName)
	}

	if err := providerConfig.ApplyBundledRequestParams(ctx); err != nil {
		_ = util.ErrorHandler("ai-proxy.apply_bundled_req_params_failed", fmt.Errorf("failed to apply bundled request params: %v", err))
		return types.ActionContinue
	}

	return types.ActionContinue
}

func rewriteResponsesBridgePathIfNeeded(ctx wrapper.HttpContext, providerConfig *provider.ProviderConfig, apiName provider.ApiName) {
	if providerConfig == nil || apiName != provider.ApiNameResponses || !providerConfig.EnableResponsesViaChatCompletionsBridge() {
		return
	}
	// 这里不能放在 RequestHeadersHandler 分支内: 不自定义请求头的 provider
	// 也必须先把 /responses 改写成 /chat/completions, 请求体转换才能继续生效。
	currentPath, _ := proxywasm.GetHttpRequestHeader(util.HeaderPath)
	if currentPath == "" {
		currentPath = ctx.Path()
	}
	switch {
	case provider.IsResponsesPath(currentPath):
		newPath := strings.Replace(currentPath, provider.PathOpenAIResponses, provider.PathOpenAIChatCompletions, 1)
		_ = proxywasm.ReplaceHttpRequestHeader(util.HeaderPath, newPath)
		ctx.SetContext(provider.ResponsesViaChatCompletionsBridgeActivatedContextKey(), true)
		log.Debugf("[Auto Protocol] Responses request detected, effective upstream path rewritten from %s to %s", currentPath, newPath)
	case provider.IsChatCompletionsPath(currentPath):
		// openaiCustomUrl 可能已直接指向 /chat/completions。此时无需再改写 path，
		// 但仍要标记请求体需要从 Responses 转成 Chat Completions。
		ctx.SetContext(provider.ResponsesViaChatCompletionsBridgeActivatedContextKey(), true)
	}
}

func onHttpRequestBody(ctx wrapper.HttpContext, pluginConfig config.PluginConfig, body []byte) types.Action {
	activeProvider := pluginConfig.GetProvider()

	if activeProvider == nil {
		log.Debugf("[onHttpRequestBody] no active provider, skip processing")
		return types.ActionContinue
	}
	log.Debugf("[onHttpRequestBody] provider=%s", activeProvider.GetProviderType())

	var action types.Action
	if handler, ok := activeProvider.(provider.RequestBodyHandler); ok {
		apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
		providerConfig := pluginConfig.GetProviderConfig()
		// If retryOnFailure is enabled, save the transformed body to the context in case of retry
		if providerConfig.IsRetryOnFailureEnabled() {
			ctx.SetContext(provider.CtxRequestBody, body)
		}
		newBody, settingErr := providerConfig.ReplaceByCustomSettings(body)
		if settingErr != nil {
			log.Errorf("failed to replace request body by custom settings: %v", settingErr)
		}
		// 仅 /v1/chat/completions 和 /v1/completions 接口支持 stream_options 参数
		if providerConfig.IsOpenAIProtocol() && (apiName == provider.ApiNameChatCompletion || apiName == provider.ApiNameCompletion) {
			newBody = normalizeOpenAiRequestBody(ctx, newBody)
		}
		log.Debugf("[onHttpRequestBody] newBody=%s", newBody)
		body = newBody

		if handlerAction, err := handler.OnRequestBody(ctx, apiName, body); err != nil {
			requestId := util.GetRequestID()
			log.Errorf("failed to process request body of request %s: %v", requestId, err)
			log.Errorf("request body of request %s:\n%s", requestId, body)
			_ = util.ProcessReqBodyErrorHandler("ai-proxy.proc_req_body_failed", fmt.Errorf("failed to process request body: %w", err))
			return types.ActionContinue
		} else {
			action = handlerAction
		}
	}

	if err := pluginConfig.GetProviderConfig().ApplyBundledRequestParams(ctx); err != nil {
		_ = util.ErrorHandler("ai-proxy.apply_bundled_req_params_failed", fmt.Errorf("failed to apply bundled request params: %v", err))
		return types.ActionContinue
	}

	return action
}

func onHttpResponseHeaders(ctx wrapper.HttpContext, pluginConfig config.PluginConfig) types.Action {
	if !wrapper.IsResponseFromUpstream() {
		// Response is not coming from the upstream. Let it pass through.
		ctx.DontReadResponseBody()
		return types.ActionContinue
	}

	activeProvider := pluginConfig.GetProvider()

	if activeProvider == nil {
		log.Debugf("[onHttpResponseHeaders] no active provider, skip processing")
		ctx.DontReadResponseBody()
		return types.ActionContinue
	}

	log.Debugf("[onHttpResponseHeaders] provider=%s", activeProvider.GetProviderType())

	providerConfig := pluginConfig.GetProviderConfig()
	apiTokenInUse := providerConfig.GetApiTokenInUse(ctx)
	apiTokens := providerConfig.GetAvailableApiToken(ctx)

	status, err := proxywasm.GetHttpResponseHeader(":status")
	if err != nil || status != "200" {
		if err != nil {
			log.Errorf("unable to load :status header from response: %v", err)
		}
		ctx.DontReadResponseBody()
		return providerConfig.OnRequestFailed(activeProvider, ctx, apiTokenInUse, apiTokens, status)
	}

	// Reset ctxApiTokenRequestFailureCount if the request is successful,
	// the apiToken is removed only when the number of consecutive request failures exceeds the threshold.
	providerConfig.ResetApiTokenRequestFailureCount(apiTokenInUse)

	apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
	headers := util.GetResponseHeaders()
	bridgeResponsesToChat := isResponsesViaChatCompletionsBridgeActivated(ctx, providerConfig)
	if handler, ok := activeProvider.(provider.TransformResponseHeadersHandler); ok {
		headerAPIName := apiName
		if bridgeResponsesToChat {
			headerAPIName = provider.ApiNameChatCompletion
		}
		handler.TransformResponseHeaders(ctx, headerAPIName, headers)
	} else {
		providerConfig.DefaultTransformResponseHeaders(ctx, headers)
	}
	util.ReplaceResponseHeaders(headers)

	// For original mode, skip body processing
	if provider.IsOriginalProtocol(ctx) {
		log.Tracef("[onHttpResponseHeaders] original mode detected, will skip body processing")
		ctx.DontReadResponseBody()
		return types.ActionContinue
	}

	_, needHandleBody := activeProvider.(provider.TransformResponseBodyHandler)
	var needHandleStreamingBody bool
	_, needHandleStreamingBody = activeProvider.(provider.StreamingResponseBodyHandler)
	if !needHandleStreamingBody {
		_, needHandleStreamingBody = activeProvider.(provider.StreamingEventHandler)
	}

	// Check if we need to read body for Claude response conversion
	needClaudeConversion, _ := ctx.GetContext("needClaudeResponseConversion").(bool)
	if !needHandleBody && !needHandleStreamingBody && !needClaudeConversion {
		ctx.DontReadResponseBody()
	} else {
		checkStream(ctx)
	}

	return types.ActionContinue
}

func onStreamingResponseBody(ctx wrapper.HttpContext, pluginConfig config.PluginConfig, chunk []byte, isLastChunk bool) []byte {

	activeProvider := pluginConfig.GetProvider()

	if activeProvider == nil {
		log.Debugf("[onStreamingResponseBody] no active provider, skip processing")
		return chunk
	}

	log.Debugf("[onStreamingResponseBody] provider=%s", activeProvider.GetProviderType())
	log.Debugf("[onStreamingResponseBody] isLastChunk=%v chunk: %s", isLastChunk, string(chunk))

	if handler, ok := activeProvider.(provider.StreamingResponseBodyHandler); ok {
		apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
		if isResponsesViaChatCompletionsBridgeActivated(ctx, pluginConfig.GetProviderConfig()) {
			apiName = provider.ApiNameChatCompletion
		}
		modifiedChunk, err := handler.OnStreamingResponseBody(ctx, apiName, chunk, isLastChunk)
		if err == nil && modifiedChunk != nil {
			return convertStreamingResponseToPublicProtocol(ctx, pluginConfig.GetProviderConfig(), modifiedChunk, isLastChunk)
		}
		return chunk
	}
	if handler, ok := activeProvider.(provider.StreamingEventHandler); ok {
		apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
		if isResponsesViaChatCompletionsBridgeActivated(ctx, pluginConfig.GetProviderConfig()) {
			apiName = provider.ApiNameChatCompletion
		}
		events := provider.ExtractStreamingEvents(ctx, chunk)
		log.Debugf("[onStreamingResponseBody] %d events received", len(events))
		if len(events) == 0 {
			// No events are extracted, return empty bytes slice
			return []byte("")
		}
		var responseBuilder strings.Builder
		for _, event := range events {
			log.Debugf("processing event: %v", event)

			if event.IsEndData() {
				responseBuilder.WriteString(event.ToHttpString())
				continue
			}

			outputEvents, err := handler.OnStreamingEvent(ctx, apiName, event)
			if err != nil {
				log.Errorf("[onStreamingResponseBody] failed to process streaming event: %v\n%s", err, chunk)
				return chunk
			}
			if outputEvents == nil {
				responseBuilder.WriteString(event.ToHttpString())
			} else if len(outputEvents) == 0 {
				// Event is filtered out, do nothing
			} else {
				for _, outputEvent := range outputEvents {
					responseBuilder.WriteString(outputEvent.ToHttpString())
				}
			}
		}

		result := []byte(responseBuilder.String())
		return convertStreamingResponseToPublicProtocol(ctx, pluginConfig.GetProviderConfig(), result, isLastChunk)
	}

	// If provider doesn't implement any streaming handlers but we need Claude conversion
	// First extract complete events from the chunk
	events := provider.ExtractStreamingEvents(ctx, chunk)
	log.Debugf("[onStreamingResponseBody] %d events received (no handler)", len(events))
	if len(events) == 0 {
		// No events are extracted, return empty bytes slice
		return []byte("")
	}

	// Build response from extracted events (without handler processing)
	var responseBuilder strings.Builder
	for _, event := range events {
		responseBuilder.WriteString(event.ToHttpString())
	}

	result := []byte(responseBuilder.String())
	return convertStreamingResponseToPublicProtocol(ctx, pluginConfig.GetProviderConfig(), result, isLastChunk)
}

func onHttpResponseBody(ctx wrapper.HttpContext, pluginConfig config.PluginConfig, body []byte) types.Action {
	activeProvider := pluginConfig.GetProvider()

	if activeProvider == nil {
		log.Debugf("[onHttpResponseBody] no active provider, skip processing")
		return types.ActionContinue
	}

	log.Debugf("[onHttpResponseBody] provider=%s", activeProvider.GetProviderType())

	var finalBody []byte

	if handler, ok := activeProvider.(provider.TransformResponseBodyHandler); ok {
		apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
		if isResponsesViaChatCompletionsBridgeActivated(ctx, pluginConfig.GetProviderConfig()) {
			apiName = provider.ApiNameChatCompletion
		}
		transformedBody, err := handler.TransformResponseBody(ctx, apiName, body)
		if err != nil {
			_ = util.ErrorHandler("ai-proxy.proc_resp_body_failed", fmt.Errorf("failed to process response body: %v", err))
			return types.ActionContinue
		}
		finalBody = transformedBody
	} else {
		finalBody = body
	}

	convertedBody, err := convertResponseBodyToPublicProtocol(ctx, pluginConfig.GetProviderConfig(), finalBody)
	if err != nil {
		_ = util.ErrorHandler("ai-proxy.convert_resp_to_public_protocol_failed", err)
		return types.ActionContinue
	}

	if err = provider.ReplaceResponseBody(convertedBody); err != nil {
		_ = util.ErrorHandler("ai-proxy.replace_resp_body_failed", fmt.Errorf("failed to replace response body: %v", err))
	}
	return types.ActionContinue
}

// saveOriginalHeaders 把入口的 host/path/auth 存到 X-ENVOY-ORIGINAL-* 头,
// 供后续阶段(如 azure 的 GetOriginalRequestPath)在这些值被改写后仍能取到原始值。
// 用 defer 在请求头处理末尾执行,传入改写前的原始值,避免存到已改写的 path。
// 仅在未设时写入,避免覆盖 async http callback 已写入的值。
func saveOriginalHeaders(originalHost, originalPath, originalAuth string) {
	if originalHost != "" {
		if saved, _ := proxywasm.GetHttpRequestHeader(util.HeaderOriginalHost); saved == "" {
			_ = proxywasm.ReplaceHttpRequestHeader(util.HeaderOriginalHost, originalHost)
		}
	}
	if originalPath != "" {
		if saved, _ := proxywasm.GetHttpRequestHeader(util.HeaderOriginalPath); saved == "" {
			_ = proxywasm.ReplaceHttpRequestHeader(util.HeaderOriginalPath, originalPath)
		}
	}
	if originalAuth != "" {
		if saved, _ := proxywasm.GetHttpRequestHeader(util.HeaderOriginalAuth); saved == "" {
			_ = proxywasm.ReplaceHttpRequestHeader(util.HeaderOriginalAuth, originalAuth)
		}
	}
}

func isResponsesViaChatCompletionsBridgeActivated(ctx wrapper.HttpContext, providerConfig *provider.ProviderConfig) bool {
	if providerConfig == nil || !providerConfig.EnableResponsesViaChatCompletionsBridge() {
		return false
	}
	return ctx.GetBoolContext(provider.ResponsesViaChatCompletionsBridgeActivatedContextKey(), false)
}

func convertStreamingResponseToPublicProtocol(ctx wrapper.HttpContext, providerConfig *provider.ProviderConfig, data []byte, isLastChunk bool) []byte {
	convertedData, err := convertStreamingResponseToResponses(ctx, providerConfig, data, isLastChunk)
	if err != nil {
		return data
	}
	convertedData, err = convertStreamingResponseToClaude(ctx, convertedData)
	if err != nil {
		return convertedData
	}
	return convertedData
}

func convertResponseBodyToPublicProtocol(ctx wrapper.HttpContext, providerConfig *provider.ProviderConfig, body []byte) ([]byte, error) {
	convertedBody, err := convertResponseBodyToResponses(ctx, providerConfig, body)
	if err != nil {
		return body, err
	}
	return convertResponseBodyToClaude(ctx, convertedBody)
}

func convertStreamingResponseToResponses(ctx wrapper.HttpContext, providerConfig *provider.ProviderConfig, data []byte, isLastChunk bool) ([]byte, error) {
	if !isResponsesViaChatCompletionsBridgeActivated(ctx, providerConfig) {
		return data, nil
	}

	var bridge *provider.ResponsesChatCompletionBridge
	if bridgeData := ctx.GetContext(provider.ResponsesViaChatCompletionsBridgeContextKey()); bridgeData != nil {
		if converter, ok := bridgeData.(*provider.ResponsesChatCompletionBridge); ok {
			bridge = converter
		}
	}
	if bridge == nil {
		bridge = &provider.ResponsesChatCompletionBridge{}
		if toolNameMap, ok := ctx.GetContext(provider.ChatCompletionToolNameMapContextKey()).(map[string]string); ok {
			bridge.ToolNameMap = toolNameMap
		}
		if toolContext, ok := ctx.GetContext(provider.ChatCompletionToolContextKey()).(*provider.ResponsesToolContext); ok {
			bridge.ToolContext = toolContext
		}
		ctx.SetContext(provider.ResponsesViaChatCompletionsBridgeContextKey(), bridge)
	}

	convertedData, err := bridge.ConvertStreamingChatCompletionToResponses(ctx, data, isLastChunk)
	if err != nil {
		log.Errorf("failed to convert streaming response to responses format: %v", err)
		return data, err
	}
	return convertedData, nil
}

func convertResponseBodyToResponses(ctx wrapper.HttpContext, providerConfig *provider.ProviderConfig, body []byte) ([]byte, error) {
	if !isResponsesViaChatCompletionsBridgeActivated(ctx, providerConfig) {
		return body, nil
	}

	var toolNameMap map[string]string
	if value, ok := ctx.GetContext(provider.ChatCompletionToolNameMapContextKey()).(map[string]string); ok {
		toolNameMap = value
	}
	var toolContext *provider.ResponsesToolContext
	if value, ok := ctx.GetContext(provider.ChatCompletionToolContextKey()).(*provider.ResponsesToolContext); ok {
		toolContext = value
	}
	convertedBody, err := provider.ConvertChatCompletionResponseToResponsesWithToolContext(body, toolContext, toolNameMap)
	if err != nil {
		return body, fmt.Errorf("failed to convert response to responses format: %v", err)
	}
	return convertedBody, nil
}

// Helper function to check if Claude response conversion is needed
func needsClaudeResponseConversion(ctx wrapper.HttpContext) bool {
	needClaudeConversion, _ := ctx.GetContext("needClaudeResponseConversion").(bool)
	return needClaudeConversion
}

// Helper function to convert OpenAI streaming response to Claude format
func convertStreamingResponseToClaude(ctx wrapper.HttpContext, data []byte) ([]byte, error) {
	if !needsClaudeResponseConversion(ctx) {
		return data, nil
	}

	// Get or create converter instance from context to maintain state
	const claudeConverterKey = "claudeConverter"
	var converter *provider.ClaudeToOpenAIConverter

	if converterData := ctx.GetContext(claudeConverterKey); converterData != nil {
		if c, ok := converterData.(*provider.ClaudeToOpenAIConverter); ok {
			converter = c
		}
	}

	if converter == nil {
		converter = &provider.ClaudeToOpenAIConverter{}
		ctx.SetContext(claudeConverterKey, converter)
	}

	claudeChunk, err := converter.ConvertOpenAIStreamResponseToClaude(ctx, data)
	if err != nil {
		log.Errorf("failed to convert streaming response to claude format: %v", err)
		return data, err
	}
	return claudeChunk, nil
}

// Helper function to convert OpenAI response body to Claude format
func convertResponseBodyToClaude(ctx wrapper.HttpContext, body []byte) ([]byte, error) {
	if !needsClaudeResponseConversion(ctx) {
		return body, nil
	}

	converter := &provider.ClaudeToOpenAIConverter{}
	convertedBody, err := converter.ConvertOpenAIResponseToClaude(ctx, body)
	if err != nil {
		return body, fmt.Errorf("failed to convert response to claude format: %v", err)
	}
	return convertedBody, nil
}

func normalizeOpenAiRequestBody(ctx wrapper.HttpContext, body []byte) []byte {
	var err error
	// Default setting include_usage.
	if gjson.GetBytes(body, "stream").Bool() {
		// Always set stream_options.include_usage to true so we can get token usage from LLM.
		// But keep the original value just in case we need it for response processing.
		includeUsage := gjson.GetBytes(body, "stream_options.include_usage").Bool()
		ctx.SetContext(ctxStreamIncludeUsage, includeUsage)
		body, err = sjson.SetBytes(body, "stream_options.include_usage", true)
		if err != nil {
			log.Errorf("set include_usage failed, err:%s", err)
		}
	}
	return body
}

func checkStream(ctx wrapper.HttpContext) {
	contentType, err := proxywasm.GetHttpResponseHeader("Content-Type")
	if err != nil || !strings.HasPrefix(contentType, "text/event-stream") || util.IsFakeStream(ctx) {
		if err != nil {
			log.Errorf("unable to load content-type header from response: %v", err)
		}
		ctx.BufferResponseBody()
		ctx.SetResponseBodyBufferLimit(defaultMaxBodyBytes)
	}
}

func getApiName(path string) provider.ApiName {
	// Check path suffix matches first
	for _, p := range pathSuffixToApiName {
		if strings.HasSuffix(path, p.key) {
			return p.value
		}
	}

	// Check path pattern matches
	for _, p := range pathPatternToApiName {
		if p.key.MatchString(path) {
			return p.value
		}
	}

	return ""
}
